version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: links_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/links_db
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Меняем порт на 3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: